// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-JJA0P4qtMZnOCGBuHrY8zcGzK_0X05c',
    appId: '1:745095155238:web:83a3e78331e9400856e0e7',
    messagingSenderId: '745095155238',
    projectId: 'e-app-e32f2',
    authDomain: 'e-app-e32f2.firebaseapp.com',
    storageBucket: 'e-app-e32f2.appspot.com',
    measurementId: 'G-3XS167K2WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_IkKS3FngYuSZ0Xcq16VMCayV46yL-Fk',
    appId: '1:745095155238:android:dcbe00de410bc2de56e0e7',
    messagingSenderId: '745095155238',
    projectId: 'e-app-e32f2',
    storageBucket: 'e-app-e32f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0tlowIBFuPQX5zFCD3Zhc4MpANcOfMMg',
    appId: '1:745095155238:ios:4eba548fe464982056e0e7',
    messagingSenderId: '745095155238',
    projectId: 'e-app-e32f2',
    storageBucket: 'e-app-e32f2.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0tlowIBFuPQX5zFCD3Zhc4MpANcOfMMg',
    appId: '1:745095155238:ios:4eba548fe464982056e0e7',
    messagingSenderId: '745095155238',
    projectId: 'e-app-e32f2',
    storageBucket: 'e-app-e32f2.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-JJA0P4qtMZnOCGBuHrY8zcGzK_0X05c',
    appId: '1:745095155238:web:26b5ec19c4fd1d9056e0e7',
    messagingSenderId: '745095155238',
    projectId: 'e-app-e32f2',
    authDomain: 'e-app-e32f2.firebaseapp.com',
    storageBucket: 'e-app-e32f2.appspot.com',
    measurementId: 'G-QTBTWTHHP7',
  );
}
